### PR TITLE
WIP: OSX build fixes

### PR DESCRIPTION
**Pull request by rvt**
This adds FindLibUSB and uses this to build the PS3 driver.

### CODE REVIEW

**Comment by sthalik** [comment]
What's there to fix? pkg-config should be capable of finding the library on its own.

**Comment by rvt** [comment]
I forgot to set this as WIP....

That said, for me, libusb was not found on OSX so I changed to use 'the cmake way' this should also work on Linux. 

I am a bit fuzzy about MSVC vs WIN32, I dont know a lot about Windows build tool chains...

I have been working on travis for the OSX build (https://travis-ci.org/rvt/opentrack) (https://github.com/rvt/opentrack/blob/travis/.travis.yml) and ran into issues before. I have seen you have been using appveyor but I couldn't find the build configuration for it...

I did see that this patch isn't working in your build according to https://ci.appveyor.com/project/sthalik/opentrack so I will have to take a look at it..

where can I find the build config for appveyor??

**Comment by sthalik** [comment]
https://gist.github.com/sthalik/3ebb3822047272e700bc5108f392f69c

**Comment by rvt** [comment]
Decided not to venture this at the moment...

**Pull request closed without merging**
